version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file: .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    command: mysqld --sql_mode=""

volumes:
  db:
    driver: local
