name: Pull request quality checks

on: pull_request

jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    env:
      DB_TEST_USER: zb_dev_db_user
      DB_TEST_NAME: zb_dev_db
      DB_TEST_PASSWORD: 0aOgrFY5XN3ALOEDyo6rO1LKCtadgWdM
      DB_TEST_HOST: ddpg-cdpd4802i3mo9mrrqb90-a.oregon-postgres.render.com
      DB_TEST_SSL: true
      NODE_ENV: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run prettier
        run: npm run format
